server:
  port: 8002
  servlet.context-path: /service
  undertow.max-http-post-size: 0

spring:
  application.name: sample-service
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent

activemq:
  listener.auto-startup: true
  url: tcp://localhost:61616

orchestrator.url: http://localhost:8001/orches/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE