spring.main.web-application-type: none
camel:
  springboot.main-run-controller: true
  threadpool:
    pool-size: 10
    max-queue-size: 1000
  dataformat:
    jackson.auto-discover-object-mapper: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE